# 工作流名称
name: Auto Build Artisan Docker Latest

# 触发条件：推送到main分支、创建v开头的标签时触发
on:
  # push:
  #   branches: [ "main" ]  # 替换为你的主分支（如master）
  #   tags: [ 'v*' ]        # 标签以v开头时触发（如v1.0.0）
  # 可选：手动触发（方便测试）
# 定义任务
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 获取 Artisan 最新 Release
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: artisan-roaster-scope/artisan
          
      - name: 解析版本号
        run: echo "VERSION=${{ steps.latest.outputs.release }}" >> $GITHUB_ENV
  
          
     # 步骤3：设置 QEMU（多架构构建需要）
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3     
        
      # 步骤4：设置Docker Buildx（增强构建能力，支持多平台）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # 确保安装最新版Buildx，支持多架构
          
      # 步骤5：登录Docker Hub（使用配置的密钥）
      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 多架构构建并推送
      - name: 构建并推送
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/artisan-web:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/artisan-web:${{ env.VERSION }}
